feat(examples): Introduce HTTP Rust server as example
unikraft/catalog-for-maintainers pull request #14
Opened 2023-11-28 22:06 UTC by razvand

Introduce an HTTP Rust server as binary compatibility run. Build server as a PIE application using `Dockerfile`. Then run it with the `base` kernel images from `../../kernels/`.

Add typical files for a bincompat app:

* `Kraftfile`: build / run rules, including pulling the `base` image
* `Dockerfile`: filesystem, including binary and libraries
* `Makefile`: used to generate the root filesystem from the `Dockerfile` rules
* `README.md`: instructions to set up, build and run the application
* `config.yaml`: configuration file to generate scripts to the application
* `http_server.rs`: the Rust HTTP server

`config.yaml` is used to generate run scripts using the `../../utils/bincompat/generate.py` script.

The kernels in `../../kernels` are generated by running the `../../utils/bincompat/base-build-all.sh` script while inside the `../../library/base/` directory.

2023-12-05 12:36 UTC, StefanJum requested changes
See the comment, works fine otherwise.

2023-12-05 12:36 UTC, StefanJum commented on examples/http-rust1.73/Kraftfile
> +cmd: ["/server"]
```suggestion
cmd: ["/http_server"]
```

2023-12-20 14:21 UTC, Mihnea0Firoiu approved these changes
Looks good.
Reviewed-by: Mihnea Firoiu <mihneafiroiu0@gmail.com>

2023-12-21 17:05 UTC, StefanJum approved these changes
All good, thanks.

Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2024-03-19 10:41 UTC, closed without merging