feat(examples): Introduce HTTP C++ server as example
unikraft/catalog-for-maintainers pull request #16
Opened 2023-11-28 22:12 UTC by razvand

Introduce an HTTP C++ server as binary compatibility run. Build server as static PIE application using `Dockerfile`. Then run it with the `base` kernel images from `../../kernels/`.

Add typical files for a bincompat app:

* `Kraftfile`: build / run rules, including pulling the `base` image
* `Dockerfile`: filesystem, including binary and libraries
* `Makefile`: used to generate the root filesystem from the `Dockerfile` rules
* `README.md`: instructions to set up, build and run the application
* `config.yaml`: configuration file to generate scripts to the application
* `http_server.cpp`: the C++ HTTP server

`config.yaml` is used to generate run scripts using the `../../utils/bincompat/generate.py` script.

The kernels in `../../kernels` are generated by running the `../../utils/bincompat/base-build-all.sh` script while inside the `../../library/base/` directory.

2023-12-21 17:03 UTC, StefanJum requested changes
I get this error while running the application, it's weird since the files seem to be copied correctly in the filesystem:
```
http_server: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

2023-12-22 22:23 UTC, Mihnea0Firoiu requested changes
I assume the port is `8080`, not `8008`.

2023-12-22 22:23 UTC, Mihnea0Firoiu commented on examples/http-cpp-bin/README.md
> +kraft run -M 128M -p 8008:8080
```suggestion
kraft run -M 128M -p 8080:8080
```

2023-12-22 22:23 UTC, Mihnea0Firoiu commented on examples/http-cpp-bin/README.md
> +Once executed, it will open port `8008` and wait for connections, and can be queried.
```suggestion
Once executed, it will open port `8080` and wait for connections, and can be queried.
```

2024-03-19 10:38 UTC, closed without merging