feat(examples): Add common README.md
unikraft/catalog-for-maintainers pull request #20
Opened 2023-12-01 09:46 UTC by razvand

The common `README.md` file in the `examples/` directory contains common instruction for setting up, configuring, building, running, using and testing applications stored in subdirectories. Specific instructions are to be handled by individual `README.md` file in each application / example subdirectory.

2023-12-04 12:21 UTC, StefanJum requested changes
Looks good @razvand, few minor comments.

2023-12-04 12:21 UTC, StefanJum commented on examples/README.md
> +Application running in binary compatibility mode use [`app-elfloader`](https://github.com/unikraft/app-elfloader) images to load and run native Linux ELFs (*Executable and Linking Format* files).
```suggestion
Applications running in binary compatibility mode use [`app-elfloader`](https://github.com/unikraft/app-elfloader) images to load and run native Linux ELFs (*Executable and Linking Format* files).
```

2023-12-04 12:21 UTC, StefanJum commented on examples/README.md
> +The images are generated from using `../library/base`.
```suggestion
The images are generated using the setup under `../library/base/`.
```

2023-12-04 12:21 UTC, StefanJum commented on examples/README.md
> +* `Dockerfile`: filesystem, including binary and libraries
```suggestion
* `Dockerfile`: creates the filesystem, including binary and libraries
```

2023-12-04 12:21 UTC, StefanJum commented on examples/README.md
> +   ./run-qemu-x86_64.sh kernels/base_qemu-x86_64-strace
```suggestion
   ./run-qemu-x86_64.sh ../../kernels/base_qemu-x86_64-strace
```

2023-12-19 19:31 UTC, closed without merging

2023-12-19 19:31 UTC, razvand commented
This is superseded by #36