feat(examples): Introduce Caddy as example
unikraft/catalog-for-maintainers pull request #3
Opened 2023-11-21 16:47 UTC by razvand

Add Caddy as binary compatibility run. Build Caddy as static PIE application using `Dockerfile`. Then run it with the `base` image from the registry.

Add

* `Dockerfile`: filesystem, including binary and libraries
* `Makefile`: used to build the filesystem / export the from the `Dockerfile`
* `Kraftfile`: build / run rules, including pulling the `base` image
* `README.md`: document how to use
* `hosts`, `Caddyfile`: required Caddy configuration files

2023-11-22 08:00 UTC, StefanJum approved these changes
All good, thanks.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-11-26 15:17 UTC, Mihnea0Firoiu reviewed
I don't know if it is supposed to happen, but running **./kraft-run-qemu.sh** gives the output:
```
 E  machine(s) not found
 E  machine(s) not found
virbr0
 E  coud not find runtime 'index.unikraft.io/unikraft.org/base'
```
**kraft version:** kraft 0.7.0 (b4c61f166ade831a725e7c16edebc810f7c4329a) go1.21.2 2023-11-08T02:09:50Z

2023-11-28 11:10 UTC, razvand commented
> I don't know if it is supposed to happen, but running **./kraft-run-qemu.sh** gives the output:
> 
> ```
>  E  machine(s) not found
>  E  machine(s) not found
> virbr0
>  E  coud not find runtime 'index.unikraft.io/unikraft.org/base'
> ```
> 
> **kraft version:** kraft 0.7.0 (b4c61f166ade831a725e7c16edebc810f7c4329a) go1.21.2 2023-11-08T02:09:50Z

@Mihnea0Firoiu , it was an issue on my side. I fixed it.

2023-11-28 12:03 UTC, StefanJum requested changes
The qemu scripts work fine, the `kraft` commands/scripts show the same `could not find runtime: too many options` that I get on #5.

Also, is this not supposed to be used with the `utils/bincompat` scripts from #8 ? There is no `config.yaml` file and the scripts are in the PR as well.

2023-11-28 12:58 UTC, razvand commented on examples/caddy-2.7/README.md
> +   make export
No reason. Will fix.

2023-11-28 19:31 UTC, Mihnea0Firoiu reviewed
The scripts work as intended, however the ```kraft``` command gives the output: ```E  could not find runtime: too many options```

2023-12-04 13:20 UTC, StefanJum requested changes
One small comment.

Besides that, I would add the `protocol not available` error in the README, just so people don't get scared by it and assume something failed.

2024-06-11 17:03 UTC, closed without merging