Razvand/maintainers readme
unikraft/catalog-for-maintainers pull request #36
Opened 2023-12-17 13:38 UTC by razvand

feat(readme): Add README for maintainers
    
Add `README.maintainers.md`. This contains common instruction for setting up, configuring, building, running, using and testing applications stored in subdirectories. Specific instructions are to be handled by individual `README.md` file in each application / example subdirectory.

Currently, instructions are used for binary compatible (bincompat) applications.

2023-12-17 15:19 UTC, Mihnea0Firoiu approved these changes
Looks good.
Reviewed-by: Mihnea Firoiu <mihneafiroiu0@gmail.com>

2023-12-19 19:19 UTC, StefanJum requested changes

2023-12-19 19:19 UTC, StefanJum commented on README.maintainers.md
> +   This can be one of the following commands, depending of the location of your application directory:
```suggestion
   This can be one of the following commands, depending on the location of your application directory:
```

2023-12-19 19:19 UTC, StefanJum commented on README.maintainers.md
> +   This can be one of the following commands, depending of the location of your application directory:
```suggestion
   This can be one of the following commands, depending on the location of your application directory:
```

2023-12-19 19:19 UTC, StefanJum commented on README.maintainers.md
> +   ```
```suggestion
   ```console
```

2023-12-19 20:06 UTC, StefanJum requested changes

2023-12-19 20:06 UTC, StefanJum commented on README.maintainers.md
> +To generate these files, run one of the following commands, depending of the location of your application directory:
```suggestion
To generate these files, run one of the following commands, depending on the location of your application directory:
```

2023-12-19 20:26 UTC, StefanJum approved these changes
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-12-19 20:26 UTC, merged